baseURL= "/"
languageCode= "zh-HK"
title= "StandOlds"
# theme= "newsroom"
theme= "calligraphy"
contentDir= "./content"
# contentDir= "../standnews/md"
paginate = 20
# paginate = 3
enableInlineShortcodes = true
enableEmoji = true
environment = "production"

[params]
  tagline = "立場新聞 2015~2021 精選"
  cdn = false
  # feature = "img/screenshot.jpg"

[params.meta]
  baseOGImage = "img/screenshot.jpg"
  faviconComplete = true
  faviconSVG = true
  faviconVersion = ""
  faviconMSColor = "#00aba9"
  faviconiOSColor = "#00aba9"

[[menu.main]]
  identifier = "專題"
  name = "專題"
  url = "/topics/"
  weight = 1

[[menu.main]]
  identifier = "分類"
  name = "分類"
  url = "/categories/"
  weight = 2

[[menu.main]]
  identifier = "關於"
  name = "關於"
  url = "/about/"
  weight = 3


################################################################################
######       The block below has additional configuration settings.        #####
######         Users can edit, but for most it won't be necessary.         #####
################################################################################

[taxonomies]
  topic = "topics"
  category = "categories"

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.parser.attribute]
  block = true

[module.hugoVersion]
  extended = true
  min = "0.89.0"

[privacy.twitter]
  enableDNT = true

[privacy.vimeo]
  enableDNT = true

[privacy.youtube]
  privacyEnhanced = true
